sudo: false

language: node_js
node_js: node

addons:
  apt:
    packages:
      - sshpass

script:

after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build
  - ls
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
