sudo: false

language: node_js
node_js: node

addons:
  apt:
    packages:
      - sshpass

script:

after_success:
  - export SYMFONY_ENV=prod && composer install --no-dev -o
  - ls
  - mkdir newBuild
  - mv * newBuild
  - tar -czf package.tgz newBuild
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
