sudo: false

language: node_js
node_js: node

addons:
  apt:
    packages:
      - sshpass

script:

after_success:
  - export SYMFONY_ENV=prod && composer install --no-dev -o
  - mkdir build
  - mv * build
  - tar -czf package.tgz build
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp package.tgz -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
